# Generated by Django 5.2.8 on 2025-12-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves_app", "0001_initial"),
        ("pokemon_app", "0003_alter_pokemon_description_alter_pokemon_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="moves",
            field=models.ManyToManyField(related_name="pokemon", to="moves_app.move"),
        ),
    ]
