# Generated by Django 5.2.8 on 2025-12-23 21:32

import django.core.validators
import moves_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250,
                        validators=[moves_app.validators.validate_move_name],
                    ),
                ),
                (
                    "accuracy",
                    models.PositiveIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "pp",
                    models.PositiveIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "power",
                    models.PositiveIntegerField(
                        default=80,
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
            ],
        ),
    ]
